In [1]:
import numpy as np
import pandas as pd
import data_clean_utils
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
import dagshub
import mlflow
dagshub.init(repo_owner="rahulpatel16092005",repo_name="swiggy-delivery-time-prediction",mlflow=True)
mlflow.set_tracking_uri("https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow")

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Accessing as rahulpatel16092005

Initialized MLflow to track repo "rahulpatel16092005/swiggy-delivery-time-prediction"

Repository rahulpatel16092005/swiggy-delivery-time-prediction initialized!

In [4]:
mlflow.set_experiment("Exp 3 - RF - HP Tuning")

2026/03/31 13:00:16 INFO mlflow.tracking.fluent: Experiment with name 'Exp 3 - RF - HP Tuning' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/df802e3198114a238e9d2d5b44713898', creation_time=1774942218178, experiment_id='4', last_update_time=1774942218178, lifecycle_stage='active', name='Exp 3 - RF - HP Tuning', tags={}, workspace='default'>

In [5]:
from sklearn import set_config

set_config(transform_output="pandas")

In [6]:
df=pd.read_csv("swiggy_cleaned.csv")

In [7]:
df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149,short
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,BANG,25,3,friday,0,5.0,19.0,evening,20.183530,very_long
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758,short
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401,medium
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138,medium

In [8]:
# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"]

df.drop(columns=columns_to_drop, inplace=True)

df

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,32,0,10.0,morning,1.489846,short
45498,21.0,4.6,windy,jam,0,buffet,motorcycle,1.0,no,metropolitian,36,0,15.0,evening,NaN,NaN
45499,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,16,0,15.0,night,4.657195,short
45500,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,26,0,5.0,afternoon,6.232393,medium
45501,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,36,0,5.0,afternoon,12.074396,long

In [9]:
temp_df=df.copy().dropna()

In [10]:
X=temp_df.drop(columns=['time_taken'])
y=temp_df['time_taken']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)

Training data size: (30156, 15)
Testing data size: (7539, 15)

In [13]:
pt=PowerTransformer()
y_train_trans=pt.fit_transform(y_train.values.reshape(-1,1))
y_test_trans=pt.transform(y_test.values.reshape(-1,1))

In [14]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [15]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [16]:
# build a preprocessor

preprocessor = ColumnTransformer(transformers=[
    ("scale", MinMaxScaler(), num_cols),
    ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",
                                     sparse_output=False), nominal_cat_cols),
    ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],
                                      encoded_missing_value=-999,
                                      handle_unknown="use_encoded_value",
                                      unknown_value=-1), ordinal_cat_cols)
],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)


preprocessor

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [17]:
X_train_trans=preprocessor.fit_transform(X_train)
X_test_trans=preprocessor.transform(X_test)

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\compose\_column_transformer.py:978: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

In [18]:
from sklearn.ensemble import RandomForestRegressor
import optuna
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.compose import TransformedTargetRegressor

In [19]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            "n_estimators": trial.suggest_int("n_estimators",10,500),
            "max_depth": trial.suggest_int("max_depth",1,30),
            "max_features": trial.suggest_categorical("max_features",[None,"sqrt","log2"]),
            "min_samples_split": trial.suggest_int("min_samples_split",2,10),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf",1,10),
            "max_samples": trial.suggest_float("max_samples",0.5,1),
            "random_state": 42,
            "n_jobs": -1,
        }

        # log model parameters
        mlflow.log_params(params)

        # build the model
        rf = RandomForestRegressor(**params)
        model = TransformedTargetRegressor(regressor=rf,transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)


        # perform cross validation
        cv_score = cross_val_score(model,
                                X_train_trans,
                                y_train,
                                cv=5,
                                scoring="neg_mean_absolute_error",
                                n_jobs=-1)

        # mean score
        mean_score = -(cv_score.mean())

        # log avg cross val error
        mlflow.log_metric("cross_val_error",mean_score)

        return mean_score

In [20]:
# create optuna study
study = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=20,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

    # train the model on best parameters
    best_rf = RandomForestRegressor(**study.best_params)

    best_rf.fit(X_train_trans,y_train_trans.values.ravel())

    # get the predictions
    y_pred_train = best_rf.predict(X_train_trans)
    y_pred_test = best_rf.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    # perform cross validation
    model = TransformedTargetRegressor(regressor=best_rf,
                                        transformer=pt)


    scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train_org))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test_org))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train_org))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test_org))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_rf,artifact_path="model")

[I 2026-03-31 13:00:57,656] A new study created in memory with name: no-name-d40d4a15-5efc-4c10-bb5f-5f30e26cd27a
  0%|          | 0/20 [00:00<?, ?it/s]

🏃 View run redolent-flea-894 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/f5916a7a883b4b298d247adb1acdb6c2
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 3. Best value: 4.31939:   5%|▌         | 1/20 [00:25<07:57, 25.12s/it]

[I 2026-03-31 13:01:23,788] Trial 3 finished with value: 4.319392137094858 and parameters: {'n_estimators': 40, 'max_depth': 5, 'max_features': None, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_samples': 0.6278514881242754}. Best is trial 3 with value: 4.319392137094858.
🏃 View run sincere-sow-412 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/5d71fc71138340a083d6d51c725a3468
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 4. Best value: 3.57006:  10%|█         | 2/20 [00:34<04:43, 15.76s/it]

[I 2026-03-31 13:01:33,031] Trial 4 finished with value: 3.570058326342192 and parameters: {'n_estimators': 69, 'max_depth': 11, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_samples': 0.571634477607341}. Best is trial 4 with value: 3.570058326342192.
🏃 View run amusing-rat-625 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/7a934ba54aeb404fbe6bbd0704fbb45f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 4. Best value: 3.57006:  15%|█▌        | 3/20 [00:40<03:09, 11.17s/it]

[I 2026-03-31 13:01:38,724] Trial 7 finished with value: 4.229317203405404 and parameters: {'n_estimators': 328, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_samples': 0.8212739778914315}. Best is trial 4 with value: 3.570058326342192.
🏃 View run grandiose-slug-810 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/44f2a7428040498aa267d4627564010e
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 6. Best value: 3.2776:  20%|██        | 4/20 [00:55<03:27, 12.96s/it]

[I 2026-03-31 13:01:54,436] Trial 6 finished with value: 3.2775957203893937 and parameters: {'n_estimators': 205, 'max_depth': 16, 'max_features': 'log2', 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_samples': 0.9574668312256874}. Best is trial 6 with value: 3.2775957203893937.
🏃 View run clean-gull-878 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/60b6d552d62f4558b367ded80bed0966
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 6. Best value: 3.2776:  25%|██▌       | 5/20 [01:05<02:58, 11.87s/it]

[I 2026-03-31 13:02:04,376] Trial 1 finished with value: 3.3703708336067786 and parameters: {'n_estimators': 357, 'max_depth': 17, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_samples': 0.8510728259336275}. Best is trial 6 with value: 3.2775957203893937.
🏃 View run auspicious-goat-206 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/4dfd5bacc6924433b42786f6a7878c25
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 2. Best value: 3.24188:  30%|███       | 6/20 [01:30<03:47, 16.22s/it]

[I 2026-03-31 13:02:29,037] Trial 2 finished with value: 3.241884077830548 and parameters: {'n_estimators': 464, 'max_depth': 20, 'max_features': 'log2', 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_samples': 0.9044810388891313}. Best is trial 2 with value: 3.241884077830548.
🏃 View run resilient-ape-584 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/673a23895352424b96e4d70fc61ec716
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 0. Best value: 3.0991:  35%|███▌      | 7/20 [02:17<05:41, 26.29s/it]

[I 2026-03-31 13:03:16,069] Trial 0 finished with value: 3.099097058237549 and parameters: {'n_estimators': 499, 'max_depth': 19, 'max_features': None, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_samples': 0.5895452884496081}. Best is trial 0 with value: 3.099097058237549.
🏃 View run spiffy-worm-576 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/04ab501294874cffb6aef902ff5ce121
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 0. Best value: 3.0991:  40%|████      | 8/20 [02:27<04:15, 21.27s/it]

[I 2026-03-31 13:03:26,579] Trial 8 finished with value: 4.226295565480732 and parameters: {'n_estimators': 458, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_samples': 0.5117566824062125}. Best is trial 0 with value: 3.099097058237549.
🏃 View run grandiose-cod-636 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/a67fafcf41c64c7493b7bd8e5e0b12b3
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 5. Best value: 3.08959:  45%|████▌     | 9/20 [02:32<02:55, 15.97s/it]

[I 2026-03-31 13:03:30,892] Trial 5 finished with value: 3.089589809196495 and parameters: {'n_estimators': 273, 'max_depth': 24, 'max_features': None, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_samples': 0.9847923245971028}. Best is trial 5 with value: 3.089589809196495.
🏃 View run bedecked-duck-867 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/f14030f524f64b8c87ff1aac0f9beea0
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 5. Best value: 3.08959:  50%|█████     | 10/20 [02:38<02:10, 13.06s/it]

[I 2026-03-31 13:03:36,877] Trial 9 finished with value: 3.20038303141616 and parameters: {'n_estimators': 129, 'max_depth': 24, 'max_features': 'sqrt', 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_samples': 0.8201636397452026}. Best is trial 5 with value: 3.089589809196495.
🏃 View run loud-grub-557 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/adec5b57b0b3486ca03045a311f6cee9
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  55%|█████▌    | 11/20 [02:56<02:10, 14.46s/it]

[I 2026-03-31 13:03:55,073] Trial 10 finished with value: 3.0759721464229353 and parameters: {'n_estimators': 177, 'max_depth': 14, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_samples': 0.8349568486026413}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run monumental-seal-850 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/89f22bfa9b1f4bf28f938d4852c75ea7
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  60%|██████    | 12/20 [03:15<02:06, 15.79s/it]

[I 2026-03-31 13:04:13,909] Trial 12 finished with value: 3.4064037731626207 and parameters: {'n_estimators': 406, 'max_depth': 13, 'max_features': 'log2', 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_samples': 0.7494604833668207}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run unique-gull-389 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/b32e01df688d4387acf12cb76349daaa
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  65%|██████▌   | 13/20 [03:46<02:23, 20.52s/it]

[I 2026-03-31 13:04:45,151] Trial 11 finished with value: 3.099979404093614 and parameters: {'n_estimators': 307, 'max_depth': 18, 'max_features': None, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_samples': 0.5778968772723886}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run resilient-pig-389 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/118f6780dd2949d6b8a0928a194af801
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  70%|███████   | 14/20 [10:07<12:56, 129.50s/it]

🏃 View run masked-hawk-358 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/de13afafbb5d46cf818b901fc09cc48b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4
[I 2026-03-31 13:11:06,554] Trial 14 finished with value: 4.666688298329012 and parameters: {'n_estimators': 437, 'max_depth': 5, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_samples': 0.594982565706553}. Best is trial 10 with value: 3.0759721464229353.

Best trial: 10. Best value: 3.07597:  75%|███████▌  | 15/20 [10:08<07:32, 90.55s/it]

[I 2026-03-31 13:11:06,921] Trial 13 finished with value: 3.2617477679247893 and parameters: {'n_estimators': 283, 'max_depth': 25, 'max_features': 'sqrt', 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_samples': 0.7119319077478419}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run orderly-pug-94 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/e738e6f0144c47e385807cc469873776
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  80%|████████  | 16/20 [10:17<04:24, 66.06s/it]

[I 2026-03-31 13:11:16,088] Trial 15 finished with value: 5.496315541505868 and parameters: {'n_estimators': 486, 'max_depth': 3, 'max_features': 'log2', 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_samples': 0.5077519240395915}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run caring-tern-227 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/81eae8f654a741b6b188a289d5571068
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  85%|████████▌ | 17/20 [10:25<02:25, 48.48s/it]

[I 2026-03-31 13:11:23,704] Trial 16 finished with value: 3.3161451339564714 and parameters: {'n_estimators': 386, 'max_depth': 21, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_samples': 0.699958812200728}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run zealous-grouse-747 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/54b187aa5b2e42a887453af48900d305
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  90%|█████████ | 18/20 [10:48<01:21, 40.86s/it]

[I 2026-03-31 13:11:46,807] Trial 17 finished with value: 3.086587874409429 and parameters: {'n_estimators': 243, 'max_depth': 29, 'max_features': None, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_samples': 0.7152349266296683}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run peaceful-chimp-240 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/aa6deb5b6aba4d3e8ea52b21e821ad6b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597:  95%|█████████▌| 19/20 [11:14<00:36, 36.66s/it]

[I 2026-03-31 13:12:13,699] Trial 18 finished with value: 3.0882609145957955 and parameters: {'n_estimators': 224, 'max_depth': 30, 'max_features': None, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_samples': 0.9848130861260387}. Best is trial 10 with value: 3.0759721464229353.
🏃 View run defiant-shark-911 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/d2f82e39cc794be999a8c0a1647e563c
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

Best trial: 10. Best value: 3.07597: 100%|██████████| 20/20 [11:18<00:00, 33.92s/it]

[I 2026-03-31 13:12:17,089] Trial 19 finished with value: 3.0883098016530837 and parameters: {'n_estimators': 238, 'max_depth': 29, 'max_features': None, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_samples': 0.9763134717336369}. Best is trial 10 with value: 3.0759721464229353.

2026/03/31 13:12:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/31 13:12:54 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4/runs/419bc7ec401f4ef5b953062ef8f15de4
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/4

In [23]:
mlflow.set_experiment("Exp 4 - LGB - HP Tuning")

2026/03/31 13:15:59 INFO mlflow.tracking.fluent: Experiment with name 'Exp 4 - LGB - HP Tuning' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/e5d2c59da5bc4f79a897d5d7a85a9b9e', creation_time=1774943161325, experiment_id='5', last_update_time=1774943161325, lifecycle_stage='active', name='Exp 4 - LGB - HP Tuning', tags={}, workspace='default'>

In [24]:
from lightgbm import LGBMRegressor
import optuna

In [25]:
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.compose import TransformedTargetRegressor

In [26]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            "n_estimators": trial.suggest_int("n_estimators",10,200),
            "max_depth": trial.suggest_int("max_depth",1,40),
            "learning_rate": trial.suggest_float("learning_rate",0.1,0.8),
            "subsample": trial.suggest_float("subsample",0.5,1),
            "min_child_weight": trial.suggest_int("min_child_weight",5,20),
            "min_split_gain": trial.suggest_float("min_split_gain",0,10),
            "reg_lambda": trial.suggest_float("reg_lambda",0,100),
            "random_state": 42,
            "n_jobs": -1,
        }

        # log model parameters
        mlflow.log_params(params)

        xgb_reg = LGBMRegressor(**params)
        model = TransformedTargetRegressor(regressor=xgb_reg,transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)


        # perform cross validation
        cv_score = cross_val_score(model,
                                X_train_trans,
                                y_train,
                                cv=5,
                                scoring="neg_mean_absolute_error",
                                n_jobs=-1)

        # mean score
        mean_score = -(cv_score.mean())
        # log avg cross val error
        mlflow.log_metric("cross_val_error",mean_score)

        return mean_score

In [28]:
# create optuna study
study = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=50,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

    # train the model on best parameters
    best_lgbm = LGBMRegressor(**study.best_params)

    best_lgbm.fit(X_train_trans,y_train_trans.values.ravel())

    # get the predictions
    y_pred_train = best_lgbm.predict(X_train_trans)
    y_pred_test = best_lgbm.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    # perform cross validation
    model = TransformedTargetRegressor(regressor=best_lgbm,
                                        transformer=pt)


    scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train_org))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test_org))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train_org))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test_org))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_lgbm,artifact_path="model")

[I 2026-03-31 13:30:42,483] A new study created in memory with name: no-name-df4f251a-c2ad-45b6-a310-e8a087c2e66e

  0%|          | 0/50 [00:00<?, ?it/s]c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\joblib\externals\loky\process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

🏃 View run thundering-foal-317 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/1836078990bd421089611775a782be19
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run wise-doe-665 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/abf6888dbcf8481ab0ea1967487d9df4
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run delightful-moth-653 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/ce650041acf84aceb92559b8941edb9f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run rebellious-ray-504 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/ab280563f0014a30884fe574f47af84f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run brawny-hare-861 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/a1543271ad374509bdb4fa559c77b805
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run sedate-foal-94 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/3f462d7ee52b4293b264c24b02cd035c
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run trusting-bear-261 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/b9660549411d460aabe13725b14fd0b4
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run peaceful-hare-834 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/a2c8b89d4813444aa5d282ba1c7179e6
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 3. Best value: 3.72164:   2%|▏         | 1/50 [00:22<18:27, 22.61s/it]

[I 2026-03-31 13:31:07,391] Trial 3 finished with value: 3.7216391811733027 and parameters: {'n_estimators': 16, 'max_depth': 11, 'learning_rate': 0.4069788586590587, 'subsample': 0.6306370125760903, 'min_child_weight': 15, 'min_split_gain': 6.999021818383686, 'reg_lambda': 43.46968480619784}. Best is trial 3 with value: 3.7216391811733027.

Best trial: 5. Best value: 3.69355:   4%|▍         | 2/50 [00:23<07:58,  9.97s/it]

[I 2026-03-31 13:31:08,529] Trial 5 finished with value: 3.6935540736887837 and parameters: {'n_estimators': 165, 'max_depth': 37, 'learning_rate': 0.5342717168346729, 'subsample': 0.8188538034680878, 'min_child_weight': 9, 'min_split_gain': 5.790585564912533, 'reg_lambda': 31.92303433524377}. Best is trial 5 with value: 3.6935540736887837.

Best trial: 5. Best value: 3.69355:   6%|▌         | 3/50 [00:24<04:34,  5.83s/it]

[I 2026-03-31 13:31:09,431] Trial 6 finished with value: 3.8177071989799245 and parameters: {'n_estimators': 163, 'max_depth': 4, 'learning_rate': 0.5365049658084542, 'subsample': 0.5547014401972261, 'min_child_weight': 9, 'min_split_gain': 5.138179819232826, 'reg_lambda': 36.65356898419269}. Best is trial 5 with value: 3.6935540736887837.

Best trial: 7. Best value: 3.34061:   8%|▊         | 4/50 [00:25<02:58,  3.88s/it]

[I 2026-03-31 13:31:10,314] Trial 7 finished with value: 3.3406072458506166 and parameters: {'n_estimators': 121, 'max_depth': 25, 'learning_rate': 0.5952600001509787, 'subsample': 0.9655873272664983, 'min_child_weight': 7, 'min_split_gain': 0.28046015762875354, 'reg_lambda': 79.17817453305383}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  10%|█         | 5/50 [00:26<02:07,  2.83s/it]

[I 2026-03-31 13:31:11,290] Trial 0 finished with value: 3.6879893754996806 and parameters: {'n_estimators': 135, 'max_depth': 10, 'learning_rate': 0.40170079169510753, 'subsample': 0.5262840784972418, 'min_child_weight': 20, 'min_split_gain': 6.399170161995832, 'reg_lambda': 11.512743843857809}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  12%|█▏        | 6/50 [00:27<01:37,  2.21s/it]

[I 2026-03-31 13:31:12,308] Trial 1 finished with value: 3.7314437139097145 and parameters: {'n_estimators': 31, 'max_depth': 36, 'learning_rate': 0.4052383843726024, 'subsample': 0.8082488191508227, 'min_child_weight': 13, 'min_split_gain': 7.685055617671789, 'reg_lambda': 68.84534154647399}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  14%|█▍        | 7/50 [00:28<01:21,  1.89s/it]

[I 2026-03-31 13:31:13,534] Trial 2 finished with value: 3.7615799570897175 and parameters: {'n_estimators': 153, 'max_depth': 13, 'learning_rate': 0.6378684451421119, 'subsample': 0.870207556357146, 'min_child_weight': 20, 'min_split_gain': 5.286711940128851, 'reg_lambda': 0.6798044869734121}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  16%|█▌        | 8/50 [00:29<01:06,  1.58s/it]

[I 2026-03-31 13:31:14,438] Trial 4 finished with value: 3.7167580598428325 and parameters: {'n_estimators': 168, 'max_depth': 37, 'learning_rate': 0.21005887188429495, 'subsample': 0.5594290509358852, 'min_child_weight': 6, 'min_split_gain': 8.987852877868107, 'reg_lambda': 8.751577768846808}. Best is trial 7 with value: 3.3406072458506166.
🏃 View run chill-dog-854 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/95c8f66fba1b46cc9300e8048a758514
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run efficient-gnat-141 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/4338222210054d14860da55166b4c431
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run popular-ape-518 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/ca81f676bc5c4bf6a96bb0afb9377e6b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run worried-yak-484 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/87bdde8c02ed4c90945634b60e6ded33
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run victorious-deer-87 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/b46433b921b74e8e9a6c16a188bee8fb
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run likeable-bat-485 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/54f5198f7a1047d2a32761e7c84c643b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run righteous-cow-758 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/b864ec36943541e48b3d13bf59514784
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run sassy-cod-280 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/bda5a7368faf4c838210b080bdd012df
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 7. Best value: 3.34061:  18%|█▊        | 9/50 [01:02<07:45, 11.37s/it]

[I 2026-03-31 13:31:47,326] Trial 10 finished with value: 3.7237449185970966 and parameters: {'n_estimators': 105, 'max_depth': 7, 'learning_rate': 0.5039522495140513, 'subsample': 0.6926410896975805, 'min_child_weight': 12, 'min_split_gain': 7.606799912613567, 'reg_lambda': 79.05659155510627}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  20%|██        | 10/50 [01:03<05:26,  8.17s/it]

[I 2026-03-31 13:31:48,349] Trial 8 finished with value: 3.947597320948554 and parameters: {'n_estimators': 12, 'max_depth': 24, 'learning_rate': 0.12923928352516204, 'subsample': 0.5944214268356678, 'min_child_weight': 18, 'min_split_gain': 0.44169926959614747, 'reg_lambda': 22.308201301976272}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  22%|██▏       | 11/50 [01:04<03:53,  5.99s/it]

[I 2026-03-31 13:31:49,375] Trial 11 finished with value: 3.777076687052155 and parameters: {'n_estimators': 178, 'max_depth': 15, 'learning_rate': 0.23014237348545652, 'subsample': 0.5799457072229135, 'min_child_weight': 13, 'min_split_gain': 9.798520257423093, 'reg_lambda': 70.24969970268839}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  24%|██▍       | 12/50 [01:05<02:48,  4.44s/it]

[I 2026-03-31 13:31:50,294] Trial 12 finished with value: 3.71081017973962 and parameters: {'n_estimators': 163, 'max_depth': 12, 'learning_rate': 0.6905014741213313, 'subsample': 0.5862335345388641, 'min_child_weight': 5, 'min_split_gain': 4.641695315330842, 'reg_lambda': 59.6503831526596}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 7. Best value: 3.34061:  26%|██▌       | 13/50 [01:06<02:07,  3.44s/it]

[I 2026-03-31 13:31:51,426] Trial 13 finished with value: 3.792045448729558 and parameters: {'n_estimators': 191, 'max_depth': 15, 'learning_rate': 0.5611769868320678, 'subsample': 0.7043961534039522, 'min_child_weight': 5, 'min_split_gain': 8.055914538442826, 'reg_lambda': 1.8502117329862067}. Best is trial 7 with value: 3.3406072458506166.

Best trial: 9. Best value: 3.18352:  28%|██▊       | 14/50 [01:07<01:40,  2.80s/it]

[I 2026-03-31 13:31:52,753] Trial 9 finished with value: 3.18351631442306 and parameters: {'n_estimators': 55, 'max_depth': 38, 'learning_rate': 0.3793573829129576, 'subsample': 0.8823899203273144, 'min_child_weight': 18, 'min_split_gain': 0.0366641615279395, 'reg_lambda': 39.450748935859494}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  30%|███       | 15/50 [01:08<01:15,  2.14s/it]

[I 2026-03-31 13:31:53,370] Trial 14 finished with value: 3.356451725878595 and parameters: {'n_estimators': 110, 'max_depth': 18, 'learning_rate': 0.5181861639546207, 'subsample': 0.7216120662817587, 'min_child_weight': 8, 'min_split_gain': 0.2508814156345385, 'reg_lambda': 39.91683677969714}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  32%|███▏      | 16/50 [01:09<01:00,  1.79s/it]

[I 2026-03-31 13:31:54,339] Trial 15 finished with value: 3.7445538932789306 and parameters: {'n_estimators': 182, 'max_depth': 15, 'learning_rate': 0.10656577361511788, 'subsample': 0.532158289103964, 'min_child_weight': 8, 'min_split_gain': 8.504206522697416, 'reg_lambda': 18.050638744529223}. Best is trial 9 with value: 3.18351631442306.
🏃 View run melodic-trout-355 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/16c5a024f8364ca1abfa3ad531f8105c
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run enchanting-steed-59 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/a5a3f0da8da548d3a0f798ea24a98e21
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run judicious-gnu-444 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/8447b5cade1c49019e4acd1671c54271
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run stately-grouse-491 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/5f5124a0d40d49f89797ef734ceab772
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run loud-ant-67 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/05a23b91c4494c74b8e23ed02441a8a1
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run receptive-stag-755 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/7b59567b32b24a9aa5c097de288086be
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run languid-cod-876 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/1c90235532f541ac875e51347754c17b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run burly-gnat-302 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/6ea73e3caaa84a32bc72587467a015be
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.18352:  34%|███▍      | 17/50 [01:42<06:08, 11.18s/it]

[I 2026-03-31 13:32:27,349] Trial 16 finished with value: 3.5569951270595297 and parameters: {'n_estimators': 53, 'max_depth': 27, 'learning_rate': 0.764817734862857, 'subsample': 0.9973646982265426, 'min_child_weight': 16, 'min_split_gain': 2.138016384001857, 'reg_lambda': 91.58405886153608}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  36%|███▌      | 18/50 [01:43<04:19,  8.11s/it]

[I 2026-03-31 13:32:28,327] Trial 17 finished with value: 3.5020140469980845 and parameters: {'n_estimators': 63, 'max_depth': 28, 'learning_rate': 0.3005508143936879, 'subsample': 0.9899598114267902, 'min_child_weight': 16, 'min_split_gain': 1.7104876445164747, 'reg_lambda': 98.11733426716069}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  38%|███▊      | 19/50 [01:44<03:05,  5.97s/it]

[I 2026-03-31 13:32:29,310] Trial 18 finished with value: 3.529739537143429 and parameters: {'n_estimators': 61, 'max_depth': 27, 'learning_rate': 0.3090364291366629, 'subsample': 0.9965779288155749, 'min_child_weight': 16, 'min_split_gain': 2.0524963454492213, 'reg_lambda': 94.69420075924465}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  40%|████      | 20/50 [01:45<02:14,  4.49s/it]

[I 2026-03-31 13:32:30,358] Trial 19 finished with value: 3.593405687593344 and parameters: {'n_estimators': 51, 'max_depth': 31, 'learning_rate': 0.2896241750072764, 'subsample': 0.9784454440653109, 'min_child_weight': 16, 'min_split_gain': 2.599620489771555, 'reg_lambda': 93.85256906431968}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  42%|████▏     | 21/50 [01:46<01:41,  3.50s/it]

[I 2026-03-31 13:32:31,539] Trial 20 finished with value: 3.5423848581105433 and parameters: {'n_estimators': 51, 'max_depth': 29, 'learning_rate': 0.3321533514694389, 'subsample': 0.9952383513837935, 'min_child_weight': 17, 'min_split_gain': 2.213224712430304, 'reg_lambda': 87.74656938066634}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  44%|████▍     | 22/50 [01:47<01:15,  2.69s/it]

[I 2026-03-31 13:32:32,340] Trial 21 finished with value: 3.568990833318187 and parameters: {'n_estimators': 63, 'max_depth': 29, 'learning_rate': 0.7899027305487385, 'subsample': 0.9985994589003444, 'min_child_weight': 17, 'min_split_gain': 2.042101896591439, 'reg_lambda': 97.05592993204496}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  46%|████▌     | 23/50 [01:48<01:01,  2.27s/it]

[I 2026-03-31 13:32:33,615] Trial 22 finished with value: 3.5371330885706556 and parameters: {'n_estimators': 61, 'max_depth': 28, 'learning_rate': 0.31550358950573126, 'subsample': 0.9998020033373445, 'min_child_weight': 16, 'min_split_gain': 2.0871296090347693, 'reg_lambda': 95.79572118482535}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  48%|████▊     | 24/50 [01:49<00:47,  1.83s/it]

[I 2026-03-31 13:32:34,435] Trial 23 finished with value: 3.5467171946780227 and parameters: {'n_estimators': 67, 'max_depth': 28, 'learning_rate': 0.7656344938146358, 'subsample': 0.9993705475305601, 'min_child_weight': 17, 'min_split_gain': 1.9717572377181882, 'reg_lambda': 92.57024165261754}. Best is trial 9 with value: 3.18351631442306.
🏃 View run respected-chimp-952 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/cf91206169f84080936b33d163ecd79e
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run resilient-pig-77 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/e65d683aed3f4f5695e9df2fdbd7ae3b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run fortunate-slug-743 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/46be54da4e024405a7a339bc25919a33
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run rambunctious-dog-801 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/6a43ab1631284f2f92288268e2536010
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run orderly-colt-337 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/9fbbaf09f38e477c8ef64a01cbad7cc8
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run judicious-rat-952 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/b5d28a1da4ef49129007482377e072ea
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run salty-sloth-10 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/164c8bb9f9e848139ae080ef644cb0fa
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run zealous-snake-167 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/c427aa504d66493ba96d45bd704fd10d
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.18352:  50%|█████     | 25/50 [02:22<04:40, 11.20s/it]

[I 2026-03-31 13:33:07,506] Trial 24 finished with value: 3.246275930124722 and parameters: {'n_estimators': 102, 'max_depth': 20, 'learning_rate': 0.5935476918569292, 'subsample': 0.9227910179466928, 'min_child_weight': 7, 'min_split_gain': 0.03797086820170642, 'reg_lambda': 57.09121416152877}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  52%|█████▏    | 26/50 [02:23<03:14,  8.09s/it]

[I 2026-03-31 13:33:08,325] Trial 25 finished with value: 3.2585466991987517 and parameters: {'n_estimators': 101, 'max_depth': 20, 'learning_rate': 0.6108781649103197, 'subsample': 0.9166430304446753, 'min_child_weight': 11, 'min_split_gain': 0.06121015705932198, 'reg_lambda': 54.59093598571509}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  54%|█████▍    | 27/50 [02:24<02:17,  5.97s/it]

[I 2026-03-31 13:33:09,350] Trial 26 finished with value: 3.297931333241243 and parameters: {'n_estimators': 100, 'max_depth': 20, 'learning_rate': 0.6140462420812781, 'subsample': 0.9200829947585367, 'min_child_weight': 11, 'min_split_gain': 0.1461757023569104, 'reg_lambda': 49.562927882912014}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  56%|█████▌    | 28/50 [02:25<01:37,  4.45s/it]

[I 2026-03-31 13:33:10,270] Trial 27 finished with value: 3.308706564456833 and parameters: {'n_estimators': 99, 'max_depth': 21, 'learning_rate': 0.6154082977792952, 'subsample': 0.9197459509349826, 'min_child_weight': 11, 'min_split_gain': 0.07014844507829476, 'reg_lambda': 51.76779951448448}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  58%|█████▊    | 29/50 [02:27<01:15,  3.58s/it]

[I 2026-03-31 13:33:11,815] Trial 28 finished with value: 3.2418692905218265 and parameters: {'n_estimators': 102, 'max_depth': 20, 'learning_rate': 0.46858758108844234, 'subsample': 0.9200428195589075, 'min_child_weight': 11, 'min_split_gain': 0.14964896967557811, 'reg_lambda': 53.405529680322786}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  60%|██████    | 30/50 [02:27<00:54,  2.72s/it]

[I 2026-03-31 13:33:12,517] Trial 29 finished with value: 3.245952830418621 and parameters: {'n_estimators': 102, 'max_depth': 20, 'learning_rate': 0.621011418340338, 'subsample': 0.9216469725463525, 'min_child_weight': 11, 'min_split_gain': 0.059529906692812384, 'reg_lambda': 50.26286206129342}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  62%|██████▏   | 31/50 [02:28<00:40,  2.13s/it]

[I 2026-03-31 13:33:13,283] Trial 30 finished with value: 3.217833692687482 and parameters: {'n_estimators': 106, 'max_depth': 22, 'learning_rate': 0.6263171064793255, 'subsample': 0.9278845627495281, 'min_child_weight': 11, 'min_split_gain': 0.008711851024337691, 'reg_lambda': 52.17145994085256}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  64%|██████▍   | 32/50 [02:29<00:32,  1.80s/it]

[I 2026-03-31 13:33:14,301] Trial 31 finished with value: 3.2334346368826132 and parameters: {'n_estimators': 105, 'max_depth': 20, 'learning_rate': 0.6184239191798838, 'subsample': 0.9240629567902935, 'min_child_weight': 11, 'min_split_gain': 0.02774097693717259, 'reg_lambda': 51.020530399787326}. Best is trial 9 with value: 3.18351631442306.
🏃 View run chill-snail-505 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/b3a9e5d00f69425bbf4515f100f0e533
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run dapper-stoat-306 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/cbb54adfa499479589950a9bc91a1c6b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run caring-bird-925 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/203bbb2aa9194f38b45df207ec61c807
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run resilient-gull-100 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/e2d2d7012b5a45b5942d2ad38260d070
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run thundering-rat-563 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/f86406beefb144b3829ae242bd12fe7d
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run worried-flea-428 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/b0d33646bae24cb9954106acb6f8decb
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run loud-shrimp-32 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/efd1695c9b6d4540b85008f96d7e5653
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run salty-ox-567 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/db2575584460486dae77f7e499e64edc
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.18352:  66%|██████▌   | 33/50 [03:02<03:09, 11.17s/it]

[I 2026-03-31 13:33:47,348] Trial 32 finished with value: 3.4609904803795075 and parameters: {'n_estimators': 135, 'max_depth': 40, 'learning_rate': 0.4604493792204404, 'subsample': 0.8550873334299895, 'min_child_weight': 10, 'min_split_gain': 1.0251980952982183, 'reg_lambda': 28.676954632397248}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  68%|██████▊   | 34/50 [03:03<02:09,  8.11s/it]

[I 2026-03-31 13:33:48,303] Trial 33 finished with value: 3.44694836145351 and parameters: {'n_estimators': 85, 'max_depth': 23, 'learning_rate': 0.45301124255705083, 'subsample': 0.8622886868394742, 'min_child_weight': 14, 'min_split_gain': 1.092420396825564, 'reg_lambda': 65.47846978638047}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  70%|███████   | 35/50 [03:04<01:30,  6.00s/it]

[I 2026-03-31 13:33:49,390] Trial 34 finished with value: 3.4855688748238185 and parameters: {'n_estimators': 83, 'max_depth': 33, 'learning_rate': 0.4576356818177039, 'subsample': 0.8673623348948699, 'min_child_weight': 14, 'min_split_gain': 1.154179073324499, 'reg_lambda': 62.95554208223332}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  72%|███████▏  | 36/50 [03:05<01:02,  4.47s/it]

[I 2026-03-31 13:33:50,292] Trial 35 finished with value: 3.4187578414452284 and parameters: {'n_estimators': 86, 'max_depth': 34, 'learning_rate': 0.45098519339416737, 'subsample': 0.8540461307326553, 'min_child_weight': 14, 'min_split_gain': 0.9631094942929977, 'reg_lambda': 65.41652158272336}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  74%|███████▍  | 37/50 [03:06<00:45,  3.47s/it]

[I 2026-03-31 13:33:51,436] Trial 36 finished with value: 3.452463666916381 and parameters: {'n_estimators': 82, 'max_depth': 23, 'learning_rate': 0.4623894184004768, 'subsample': 0.8557798751278904, 'min_child_weight': 14, 'min_split_gain': 1.0860352314140833, 'reg_lambda': 66.55252061128061}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  76%|███████▌  | 38/50 [03:07<00:32,  2.69s/it]

[I 2026-03-31 13:33:52,290] Trial 37 finished with value: 3.477851312747654 and parameters: {'n_estimators': 80, 'max_depth': 40, 'learning_rate': 0.4631427182143122, 'subsample': 0.8649660190341759, 'min_child_weight': 14, 'min_split_gain': 1.1485182296386838, 'reg_lambda': 64.1198794413443}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  78%|███████▊  | 39/50 [04:46<05:46, 31.53s/it]

[I 2026-03-31 13:35:31,097] Trial 39 finished with value: 3.4409502471102487 and parameters: {'n_estimators': 84, 'max_depth': 33, 'learning_rate': 0.4458511334403249, 'subsample': 0.8571275281727985, 'min_child_weight': 14, 'min_split_gain': 1.0869701355025474, 'reg_lambda': 64.47686413248961}. Best is trial 9 with value: 3.18351631442306.
[I 2026-03-31 13:35:31,105] Trial 38 finished with value: 3.4993679190612506 and parameters: {'n_estimators': 85, 'max_depth': 40, 'learning_rate': 0.4772067211665403, 'subsample': 0.8533006856312743, 'min_child_weight': 14, 'min_split_gain': 1.0283897257085306, 'reg_lambda': 30.317357796419977}. Best is trial 9 with value: 3.18351631442306.
🏃 View run incongruous-bear-772 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/4b1e8d4951b0408da34d55fd87c12c3b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run silent-wasp-952 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/7930250967b1459593c15f25e5bc52ff
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run exultant-hare-637 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/5ad825d4d26b45088e0ce695c6fc2664
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run clean-panda-273 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/ecda1eb3b69c478998c45d094ec1fcb9
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run righteous-grouse-422 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/d7c4e772b5f54844aceba8775435a6de
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run thundering-skink-248 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/181614f4f6094bc6a31f37bac832001f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5
🏃 View run respected-horse-491 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/fd322b49c7944a5b9b6edf3bb7a4e5d8
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.18352:  82%|████████▏ | 41/50 [05:08<03:18, 22.05s/it]

[I 2026-03-31 13:35:53,089] Trial 41 finished with value: 3.58013964407737 and parameters: {'n_estimators': 138, 'max_depth': 17, 'learning_rate': 0.6959763183359404, 'subsample': 0.8220659538538277, 'min_child_weight': 12, 'min_split_gain': 3.092232722115666, 'reg_lambda': 45.404454523842745}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  84%|████████▍ | 42/50 [05:09<02:14, 16.83s/it]

[I 2026-03-31 13:35:54,111] Trial 44 finished with value: 3.640844559822354 and parameters: {'n_estimators': 137, 'max_depth': 18, 'learning_rate': 0.3717812580074268, 'subsample': 0.7798087488947553, 'min_child_weight': 20, 'min_split_gain': 3.2466854233802027, 'reg_lambda': 47.04818573087833}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  86%|████████▌ | 43/50 [05:10<01:28, 12.70s/it]

[I 2026-03-31 13:35:55,136] Trial 43 finished with value: 3.6588145191654875 and parameters: {'n_estimators': 135, 'max_depth': 9, 'learning_rate': 0.6779041182162634, 'subsample': 0.7792517578592633, 'min_child_weight': 20, 'min_split_gain': 3.314475705605765, 'reg_lambda': 44.790029414988524}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  88%|████████▊ | 44/50 [05:11<00:57,  9.51s/it]

[I 2026-03-31 13:35:56,109] Trial 40 finished with value: 3.966100685998989 and parameters: {'n_estimators': 132, 'max_depth': 2, 'learning_rate': 0.6922877857312792, 'subsample': 0.8064991976211315, 'min_child_weight': 12, 'min_split_gain': 3.297682072169918, 'reg_lambda': 46.08258816434228}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  90%|█████████ | 45/50 [05:12<00:35,  7.13s/it]

[I 2026-03-31 13:35:57,127] Trial 45 finished with value: 3.6461845731913107 and parameters: {'n_estimators': 127, 'max_depth': 8, 'learning_rate': 0.6683769608917106, 'subsample': 0.8119703962837805, 'min_child_weight': 19, 'min_split_gain': 3.132986564705447, 'reg_lambda': 44.757420489857154}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  92%|█████████▏| 46/50 [05:13<00:21,  5.41s/it]

[I 2026-03-31 13:35:58,209] Trial 42 finished with value: 3.623499301288315 and parameters: {'n_estimators': 131, 'max_depth': 17, 'learning_rate': 0.674250539767802, 'subsample': 0.7926818755121916, 'min_child_weight': 19, 'min_split_gain': 3.8232961581034615, 'reg_lambda': 41.16081975698068}. Best is trial 9 with value: 3.18351631442306.
🏃 View run judicious-asp-63 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/867e3aea262148a8acb6e95b8e506043
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.18352:  94%|█████████▍| 47/50 [05:15<00:13,  4.44s/it]

[I 2026-03-31 13:36:00,275] Trial 46 finished with value: 3.741767052998651 and parameters: {'n_estimators': 144, 'max_depth': 8, 'learning_rate': 0.6670109336475253, 'subsample': 0.7791756527653824, 'min_child_weight': 20, 'min_split_gain': 5.952296029426026, 'reg_lambda': 41.447050881803115}. Best is trial 9 with value: 3.18351631442306.

Best trial: 9. Best value: 3.18352:  96%|█████████▌| 48/50 [05:18<00:07,  3.97s/it]

[I 2026-03-31 13:36:03,121] Trial 47 finished with value: 3.6550772656706827 and parameters: {'n_estimators': 138, 'max_depth': 8, 'learning_rate': 0.6710490570928678, 'subsample': 0.7885719015167107, 'min_child_weight': 19, 'min_split_gain': 3.2786293342414856, 'reg_lambda': 44.264603820883934}. Best is trial 9 with value: 3.18351631442306.
🏃 View run fun-flea-468 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/cf5601045bce41519c5531bd437ba2cf
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.18352:  98%|█████████▊| 49/50 [05:24<00:04,  4.64s/it]

[I 2026-03-31 13:36:09,368] Trial 48 finished with value: 3.436328268688154 and parameters: {'n_estimators': 117, 'max_depth': 25, 'learning_rate': 0.5738333487151315, 'subsample': 0.9475222769639077, 'min_child_weight': 10, 'min_split_gain': 0.6753676735287026, 'reg_lambda': 35.05657158812735}. Best is trial 9 with value: 3.18351631442306.
🏃 View run monumental-dog-593 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/f8164dd9680d4740aaef88636c462fd9
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.18352: 100%|██████████| 50/50 [05:26<00:00,  6.53s/it]

[I 2026-03-31 13:36:11,108] Trial 49 finished with value: 3.3405552797257982 and parameters: {'n_estimators': 117, 'max_depth': 25, 'learning_rate': 0.40453556771905885, 'subsample': 0.9430593719210822, 'min_child_weight': 10, 'min_split_gain': 0.6133405775169966, 'reg_lambda': 34.563613558540446}. Best is trial 9 with value: 3.18351631442306.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000875 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

2026/03/31 13:36:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/31 13:36:29 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5/runs/f9f8a215288748e99d3b6ed0068fa0e6
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/5