In [ ]:
import numpy as np
import pandas as pd
import data_clean_utils
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [7]:
import dagshub
import mlflow
dagshub.init(repo_owner="rahulpatel16092005",repo_name="swiggy-delivery-time-prediction",mlflow=True)
mlflow.set_tracking_uri("https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow")

Accessing as rahulpatel16092005

Initialized MLflow to track repo "rahulpatel16092005/swiggy-delivery-time-prediction"

Repository rahulpatel16092005/swiggy-delivery-time-prediction initialized!

In [8]:
mlflow.set_experiment("Exp 3 - RF HP Tuning")

<Experiment: artifact_location='mlflow-artifacts:/3432a6efc1574117b7dacd657b91b35f', creation_time=1774936048074, experiment_id='3', last_update_time=1774936048074, lifecycle_stage='active', name='Exp 3 - RF HP Tuning', tags={}, workspace='default'>

In [9]:
from sklearn import set_config

set_config(transform_output="pandas")

In [10]:
df=pd.read_csv("swiggy_cleaned.csv")

In [11]:
df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149,short
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,BANG,25,3,friday,0,5.0,19.0,evening,20.183530,very_long
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758,short
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401,medium
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138,medium

In [12]:
# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"]

df.drop(columns=columns_to_drop, inplace=True)

df

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,32,0,10.0,morning,1.489846,short
45498,21.0,4.6,windy,jam,0,buffet,motorcycle,1.0,no,metropolitian,36,0,15.0,evening,NaN,NaN
45499,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,16,0,15.0,night,4.657195,short
45500,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,26,0,5.0,afternoon,6.232393,medium
45501,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,36,0,5.0,afternoon,12.074396,long

In [13]:
temp_df=df.copy().dropna()

In [15]:
X=temp_df.drop(columns=['time_taken'])
y=temp_df['time_taken']

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)

Training data size: (30156, 15)
Testing data size: (7539, 15)

In [18]:
pt=PowerTransformer()
y_train_trans=pt.fit_transform(y_train.values.reshape(-1,1))
y_test_trans=pt.transform(y_test.values.reshape(-1,1))

In [19]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [20]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [21]:
# build a preprocessor

preprocessor = ColumnTransformer(transformers=[
    ("scale", MinMaxScaler(), num_cols),
    ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",
                                     sparse_output=False), nominal_cat_cols),
    ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],
                                      encoded_missing_value=-999,
                                      handle_unknown="use_encoded_value",
                                      unknown_value=-1), ordinal_cat_cols)
],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)


preprocessor

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [22]:
X_train_trans=preprocessor.fit_transform(X_train)
X_test_trans=preprocessor.transform(X_test)

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\compose\_column_transformer.py:978: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

In [19]:
from sklearn.ensemble import RandomForestRegressor
import optuna
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.compose import TransformedTargetRegressor

In [20]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            "n_estimators": trial.suggest_int("n_estimators",10,500),
            "max_depth": trial.suggest_int("max_depth",1,30),
            "max_features": trial.suggest_categorical("max_features",[None,"sqrt","log2"]),
            "min_samples_split": trial.suggest_int("min_samples_split",2,10),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf",1,10),
            "max_samples": trial.suggest_float("max_samples",0.5,1),
            "random_state": 42,
            "n_jobs": -1,
        }

        # log model parameters
        mlflow.log_params(params)

        # build the model
        rf = RandomForestRegressor(**params)
        model = TransformedTargetRegressor(regressor=rf,transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)


        # perform cross validation
        cv_score = cross_val_score(model,
                                X_train_trans,
                                y_train,
                                cv=5,
                                scoring="neg_mean_absolute_error",
                                n_jobs=-1)

        # mean score
        mean_score = -(cv_score.mean())

        # log avg cross val error
        mlflow.log_metric("cross_val_error",mean_score)

        return mean_score

In [22]:
# create optuna study
study = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=20,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

    # train the model on best parameters
    best_rf = RandomForestRegressor(**study.best_params)

    best_rf.fit(X_train_trans,y_train_trans.values.ravel())

    # get the predictions
    y_pred_train = best_rf.predict(X_train_trans)
    y_pred_test = best_rf.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    # perform cross validation
    model = TransformedTargetRegressor(regressor=best_rf,
                                        transformer=pt)


    scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train_org))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test_org))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train_org))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test_org))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_rf,artifact_path="model")

[I 2026-03-31 11:34:27,646] A new study created in memory with name: no-name-864b0521-f6ad-4451-b96d-7e0284d4fd93
  0%|          | 0/20 [00:00<?, ?it/s]c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

🏃 View run youthful-finch-520 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/160488ed866044e7a02101f9937f2377
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
Best trial: 0. Best value: 6.65514:   5%|▌         | 1/20 [00:10<03:27, 10.91s/it]c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

[I 2026-03-31 11:34:40,230] Trial 0 finished with value: 6.655140045164171 and parameters: {'n_estimators': 198, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_samples': 0.6637100207330306}. Best is trial 0 with value: 6.655140045164171.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

🏃 View run burly-donkey-516 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/49c7d455d0f14b42a59fad819f93c9ee
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 7. Best value: 3.25014:  10%|█         | 2/20 [00:25<03:58, 13.23s/it]

[I 2026-03-31 11:34:54,710] Trial 7 finished with value: 3.250139466957793 and parameters: {'n_estimators': 61, 'max_depth': 25, 'max_features': 'sqrt', 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_samples': 0.6626326869186211}. Best is trial 7 with value: 3.250139466957793.
🏃 View run masked-ray-854 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/7586da8762c4453b86d3fc530d0b2e30
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 7. Best value: 3.25014:  15%|█▌        | 3/20 [00:43<04:17, 15.14s/it]

[I 2026-03-31 11:35:12,495] Trial 5 finished with value: 5.911904173111981 and parameters: {'n_estimators': 96, 'max_depth': 2, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_samples': 0.9943943564523094}. Best is trial 7 with value: 3.250139466957793.
🏃 View run victorious-yak-557 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/99bc3f1022894848aa240ab001e5952a
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 6. Best value: 3.11118:  20%|██        | 4/20 [00:54<03:37, 13.59s/it]

[I 2026-03-31 11:35:23,699] Trial 6 finished with value: 3.1111819016038167 and parameters: {'n_estimators': 53, 'max_depth': 12, 'max_features': None, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_samples': 0.9629085507205222}. Best is trial 6 with value: 3.1111819016038167.
🏃 View run fun-shrimp-495 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/5eed1fa090f24c589e508be3ba7c4052
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 6. Best value: 3.11118:  25%|██▌       | 5/20 [00:56<02:20,  9.37s/it]

[I 2026-03-31 11:35:25,598] Trial 4 finished with value: 3.387808402129417 and parameters: {'n_estimators': 100, 'max_depth': 22, 'max_features': 'log2', 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_samples': 0.5819623148372157}. Best is trial 6 with value: 3.1111819016038167.
🏃 View run fearless-stork-209 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/0246d4154bf5492e9dda2b62e727d29c
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run able-doe-546 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/2f92ed5db0304f74bc2b20b67182774b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 6. Best value: 3.11118:  30%|███       | 6/20 [01:09<02:30, 10.78s/it]

[I 2026-03-31 11:35:39,029] Trial 9 finished with value: 3.7971726301045807 and parameters: {'n_estimators': 65, 'max_depth': 9, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_samples': 0.9534206978242845}. Best is trial 6 with value: 3.1111819016038167.
[I 2026-03-31 11:35:39,076] Trial 1 finished with value: 3.2316750492171264 and parameters: {'n_estimators': 255, 'max_depth': 28, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_samples': 0.6383340184657842}. Best is trial 6 with value: 3.1111819016038167.
🏃 View run valuable-eel-146 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/ad7ca6316a384af38082ce2555d2c164
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 6. Best value: 3.11118:  40%|████      | 8/20 [01:36<02:24, 12.02s/it]

[I 2026-03-31 11:36:05,680] Trial 8 finished with value: 3.412841065196319 and parameters: {'n_estimators': 426, 'max_depth': 16, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_samples': 0.715491607520643}. Best is trial 6 with value: 3.1111819016038167.
🏃 View run rogue-penguin-983 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/735595f5609a42f592715d9263b8aa2f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 6. Best value: 3.11118:  45%|████▌     | 9/20 [02:05<03:01, 16.49s/it]

[I 2026-03-31 11:36:34,892] Trial 2 finished with value: 3.1859615720018093 and parameters: {'n_estimators': 396, 'max_depth': 27, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_samples': 0.6420342301268331}. Best is trial 6 with value: 3.1111819016038167.
🏃 View run valuable-grouse-986 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/ee1379ff2f1a4afe85995eb3c241bb4a
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  50%|█████     | 10/20 [02:27<02:59, 17.92s/it]

[I 2026-03-31 11:36:56,669] Trial 3 finished with value: 3.0993197877393523 and parameters: {'n_estimators': 224, 'max_depth': 18, 'max_features': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_samples': 0.9430016342784593}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run kindly-shad-443 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/5d1b3ec657f141e18b64754e84f40708
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  55%|█████▌    | 11/20 [02:34<02:15, 15.05s/it]

[I 2026-03-31 11:37:04,313] Trial 11 finished with value: 3.551683901646242 and parameters: {'n_estimators': 170, 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_samples': 0.5084162796865119}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run charming-owl-494 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/2d5e7a697fc24d089f394585f8717951
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  60%|██████    | 12/20 [02:39<01:36, 12.12s/it]

[I 2026-03-31 11:37:09,062] Trial 10 finished with value: 3.3684533660928437 and parameters: {'n_estimators': 359, 'max_depth': 12, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_samples': 0.627474846958334}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run victorious-smelt-416 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/099d2965ffc14d66ae4e28648c4d9017
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  65%|██████▌   | 13/20 [02:47<01:16, 10.95s/it]

[I 2026-03-31 11:37:17,132] Trial 14 finished with value: 3.6843554410646866 and parameters: {'n_estimators': 232, 'max_depth': 10, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_samples': 0.7873190800887948}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run entertaining-ox-124 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/c8f781ee8afd4efaa13bb5acdea81cef
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  70%|███████   | 14/20 [03:16<01:37, 16.21s/it]

[I 2026-03-31 11:37:46,077] Trial 12 finished with value: 3.1691171118270747 and parameters: {'n_estimators': 304, 'max_depth': 30, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_samples': 0.9679924011634833}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run overjoyed-stag-986 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/e2e43e69c8de44b8ae5577dde44e7218
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  75%|███████▌  | 15/20 [03:29<01:16, 15.23s/it]

[I 2026-03-31 11:37:58,968] Trial 13 finished with value: 3.252882167275801 and parameters: {'n_estimators': 199, 'max_depth': 18, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_samples': 0.644247694098313}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run caring-bat-864 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/ffc98ca98fc54688916d310863898951
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  80%|████████  | 16/20 [03:34<00:49, 12.28s/it]

[I 2026-03-31 11:38:04,253] Trial 15 finished with value: 3.540303234811371 and parameters: {'n_estimators': 283, 'max_depth': 11, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_samples': 0.6567082861642641}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run sneaky-sheep-324 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/6de6c6648d2d4527a2e09b82f2c94207
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.09932:  85%|████████▌ | 17/20 [03:46<00:35, 11.99s/it]

[I 2026-03-31 11:38:15,561] Trial 16 finished with value: 3.3304090915251634 and parameters: {'n_estimators': 231, 'max_depth': 15, 'max_features': 'sqrt', 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_samples': 0.7586503158036212}. Best is trial 3 with value: 3.0993197877393523.
🏃 View run resilient-crow-55 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/39e7131770684f52b4d46a0756140dc1
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 17. Best value: 3.09167:  90%|█████████ | 18/20 [04:50<00:55, 27.54s/it]

[I 2026-03-31 11:39:19,448] Trial 17 finished with value: 3.0916681462884457 and parameters: {'n_estimators': 293, 'max_depth': 17, 'max_features': None, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_samples': 0.8733549972380228}. Best is trial 17 with value: 3.0916681462884457.
🏃 View run shivering-bear-573 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/43b5a7b147bf4965b3ad6a179e20929d
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 17. Best value: 3.09167:  95%|█████████▌| 19/20 [06:11<00:43, 43.44s/it]

[I 2026-03-31 11:40:40,423] Trial 19 finished with value: 3.1027211767265848 and parameters: {'n_estimators': 287, 'max_depth': 18, 'max_features': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.879048940380281}. Best is trial 17 with value: 3.0916681462884457.
🏃 View run amusing-fish-321 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/b0e3d4e639b441978451be1a478e03f3
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 17. Best value: 3.09167: 100%|██████████| 20/20 [06:28<00:00, 19.44s/it]

[I 2026-03-31 11:40:58,092] Trial 18 finished with value: 3.0988338881404807 and parameters: {'n_estimators': 337, 'max_depth': 17, 'max_features': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.8688736168259044}. Best is trial 17 with value: 3.0916681462884457.

2026/03/31 11:42:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/31 11:42:38 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/717e69d186714404bb9f0f2f49d27a6b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

In [1]:
from lightgbm import LGBMRegressor
import optuna

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.compose import TransformedTargetRegressor

In [4]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            "n_estimators": trial.suggest_int("n_estimators",10,200),
            "max_depth": trial.suggest_int("max_depth",1,40),
            "learning_rate": trial.suggest_float("learning_rate",0.1,0.8),
            "subsample": trial.suggest_float("subsample",0.5,1),
            "min_child_weight": trial.suggest_int("min_child_weight",5,20),
            "min_split_gain": trial.suggest_float("min_split_gain",0,10),
            "reg_lambda": trial.suggest_float("reg_lambda",0,100),
            "random_state": 42,
            "n_jobs": -1,
        }

        # log model parameters
        mlflow.log_params(params)

        xgb_reg = LGBMRegressor(**params)
        model = TransformedTargetRegressor(regressor=xgb_reg,transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)


        # perform cross validation
        cv_score = cross_val_score(model,
                                X_train_trans,
                                y_train,
                                cv=5,
                                scoring="neg_mean_absolute_error",
                                n_jobs=-1)

        # mean score
        mean_score = -(cv_score.mean())
        # log avg cross val error
        mlflow.log_metric("cross_val_error",mean_score)

        return mean_score

In [ ]:
# create optuna study
study = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=50,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

    # train the model on best parameters
    best_lgbm = LGBMRegressor(**study.best_params)

    best_lgbm.fit(X_train_trans,y_train_pt.values.ravel())

    # get the predictions
    y_pred_train = best_lgbm.predict(X_train_trans)
    y_pred_test = best_lgbm.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    # perform cross validation
    model = TransformedTargetRegressor(regressor=best_lgbm,
                                        transformer=pt)


    scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train_org))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test_org))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train_org))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test_org))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_lgbm,artifact_path="model")

[I 2026-03-31 12:55:27,456] A new study created in memory with name: no-name-a5bb1643-15ca-49a6-8201-9904d8bd03a8
  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run legendary-turtle-75 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/26e78f736a3b43119645fd646170e404
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 1. Best value: 3.77935:   2%|▏         | 1/50 [00:09<08:02,  9.84s/it]

[I 2026-03-31 12:55:38,599] Trial 1 finished with value: 3.7793469860394984 and parameters: {'n_estimators': 140, 'max_depth': 23, 'learning_rate': 0.6934636460588556, 'subsample': 0.7667272036347765, 'min_child_weight': 11, 'min_split_gain': 8.543712449727577, 'reg_lambda': 22.261045871215234}. Best is trial 1 with value: 3.7793469860394984.
🏃 View run flawless-skink-195 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/04df1fdddd3e41798d5811b3d52b5eb1
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run funny-grouse-551 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/aae3bf6507a24248914e70357ecf2189
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run chill-hog-566 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/a918957dc9044603acacf57a397cac6b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run salty-pug-344 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/e5a4562d2827414991c606e00a82180c
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run loud-pig-574 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/0e76e5a7df41422399db34b19f547355
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run resilient-fox-48 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/71ca23934a7c45f197178aac7c48dcdf
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.60959:   4%|▍         | 2/50 [00:22<09:21, 11.70s/it]

[I 2026-03-31 12:55:51,605] Trial 0 finished with value: 3.6095880875472184 and parameters: {'n_estimators': 185, 'max_depth': 33, 'learning_rate': 0.4081360825834872, 'subsample': 0.6256020690209401, 'min_child_weight': 13, 'min_split_gain': 3.5501125840177963, 'reg_lambda': 68.19402094740067}. Best is trial 0 with value: 3.6095880875472184.

Best trial: 4. Best value: 3.48229:   6%|▌         | 3/50 [00:24<05:41,  7.26s/it]

[I 2026-03-31 12:55:53,569] Trial 4 finished with value: 3.4822931555949856 and parameters: {'n_estimators': 137, 'max_depth': 31, 'learning_rate': 0.4885527730029391, 'subsample': 0.8444085676400508, 'min_child_weight': 12, 'min_split_gain': 0.9652696602206756, 'reg_lambda': 44.717881314890995}. Best is trial 4 with value: 3.4822931555949856.

Best trial: 4. Best value: 3.48229:   8%|▊         | 4/50 [00:26<03:56,  5.14s/it]

[I 2026-03-31 12:55:55,448] Trial 5 finished with value: 3.754079193896575 and parameters: {'n_estimators': 200, 'max_depth': 34, 'learning_rate': 0.18530143945287952, 'subsample': 0.7652449175020579, 'min_child_weight': 10, 'min_split_gain': 8.627185052726741, 'reg_lambda': 37.94934186276245}. Best is trial 4 with value: 3.4822931555949856.

Best trial: 4. Best value: 3.48229:  10%|█         | 5/50 [00:27<02:42,  3.61s/it]

[I 2026-03-31 12:55:56,382] Trial 3 finished with value: 3.71102702130037 and parameters: {'n_estimators': 143, 'max_depth': 25, 'learning_rate': 0.6973793873731737, 'subsample': 0.7939041041847537, 'min_child_weight': 14, 'min_split_gain': 6.516539924797108, 'reg_lambda': 82.43463499721815}. Best is trial 4 with value: 3.4822931555949856.

Best trial: 4. Best value: 3.48229:  12%|█▏        | 6/50 [00:28<02:02,  2.79s/it]

[I 2026-03-31 12:55:57,578] Trial 2 finished with value: 3.7321551486670352 and parameters: {'n_estimators': 110, 'max_depth': 7, 'learning_rate': 0.6369186576552586, 'subsample': 0.5969286950660941, 'min_child_weight': 18, 'min_split_gain': 8.095840899474204, 'reg_lambda': 36.237940052454235}. Best is trial 4 with value: 3.4822931555949856.

Best trial: 4. Best value: 3.48229:  14%|█▍        | 7/50 [00:29<01:32,  2.15s/it]

[I 2026-03-31 12:55:58,420] Trial 7 finished with value: 3.6157451380298986 and parameters: {'n_estimators': 181, 'max_depth': 16, 'learning_rate': 0.15184129916644076, 'subsample': 0.8990129560304727, 'min_child_weight': 14, 'min_split_gain': 3.5358470595757687, 'reg_lambda': 64.54374302739573}. Best is trial 4 with value: 3.4822931555949856.
🏃 View run big-rat-505 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/a1a45c0e0c944ae4a57038fea1eaf985
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 4. Best value: 3.48229:  16%|█▌        | 8/50 [00:39<03:16,  4.68s/it]

[I 2026-03-31 12:56:08,496] Trial 6 finished with value: 3.7696264253117677 and parameters: {'n_estimators': 150, 'max_depth': 9, 'learning_rate': 0.7256190421427199, 'subsample': 0.9881663299034347, 'min_child_weight': 8, 'min_split_gain': 7.179413937131823, 'reg_lambda': 73.70685185172145}. Best is trial 4 with value: 3.4822931555949856.
🏃 View run illustrious-colt-156 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/a22cba2c9de7444ba8ec09c19083091e
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 4. Best value: 3.48229:  18%|█▊        | 9/50 [00:50<04:32,  6.64s/it]

[I 2026-03-31 12:56:19,455] Trial 8 finished with value: 3.6084831568359528 and parameters: {'n_estimators': 156, 'max_depth': 26, 'learning_rate': 0.6261083565473328, 'subsample': 0.9737414600706429, 'min_child_weight': 15, 'min_split_gain': 2.155247475706874, 'reg_lambda': 1.7833245545605947}. Best is trial 4 with value: 3.4822931555949856.
🏃 View run loud-lamb-977 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/e37759297a544525b1cb8e43a1cf13cb
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run intrigued-gnu-811 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/20ea9636bd5d4597bc1bfd7581dcf2fa
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run unique-shad-432 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/50b3fd97529f4951a153b93c28669333
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run learned-snake-998 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/cf6f4f92359946a7a8373d69fd25bb9b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run gaudy-rat-945 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/aa135a43461d45cebede77b3a7413b00
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run big-fowl-311 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/419cb9689c68403bb27cfbaeb94280e9
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 9. Best value: 3.34256:  20%|██        | 10/50 [01:02<05:31,  8.29s/it]

[I 2026-03-31 12:56:31,435] Trial 9 finished with value: 3.3425557944839808 and parameters: {'n_estimators': 37, 'max_depth': 40, 'learning_rate': 0.18837797485200314, 'subsample': 0.6126655457566106, 'min_child_weight': 12, 'min_split_gain': 0.5383739107897956, 'reg_lambda': 52.757272878707695}. Best is trial 9 with value: 3.3425557944839808.

Best trial: 9. Best value: 3.34256:  22%|██▏       | 11/50 [01:03<03:56,  6.07s/it]

[I 2026-03-31 12:56:32,459] Trial 10 finished with value: 3.8089160306292675 and parameters: {'n_estimators': 124, 'max_depth': 6, 'learning_rate': 0.6748683432700975, 'subsample': 0.9313735913927358, 'min_child_weight': 11, 'min_split_gain': 6.919824254453022, 'reg_lambda': 91.97797900797875}. Best is trial 9 with value: 3.3425557944839808.

Best trial: 9. Best value: 3.34256:  24%|██▍       | 12/50 [01:05<03:02,  4.81s/it]

[I 2026-03-31 12:56:34,406] Trial 11 finished with value: 3.773223354477662 and parameters: {'n_estimators': 83, 'max_depth': 28, 'learning_rate': 0.17603200841351446, 'subsample': 0.5070142899087315, 'min_child_weight': 15, 'min_split_gain': 8.562504361952204, 'reg_lambda': 31.617043612143313}. Best is trial 9 with value: 3.3425557944839808.

Best trial: 9. Best value: 3.34256:  26%|██▌       | 13/50 [01:07<02:27,  3.98s/it]

[I 2026-03-31 12:56:36,454] Trial 12 finished with value: 3.518300233668409 and parameters: {'n_estimators': 20, 'max_depth': 38, 'learning_rate': 0.7654082158259452, 'subsample': 0.9425909184110669, 'min_child_weight': 13, 'min_split_gain': 1.6760165362402146, 'reg_lambda': 73.61222175251068}. Best is trial 9 with value: 3.3425557944839808.

Best trial: 9. Best value: 3.34256:  28%|██▊       | 14/50 [01:08<01:51,  3.08s/it]

[I 2026-03-31 12:56:37,478] Trial 13 finished with value: 3.7681405255806637 and parameters: {'n_estimators': 60, 'max_depth': 6, 'learning_rate': 0.6102373124919228, 'subsample': 0.76970171565641, 'min_child_weight': 14, 'min_split_gain': 8.152688671593776, 'reg_lambda': 60.614848718326876}. Best is trial 9 with value: 3.3425557944839808.

Best trial: 9. Best value: 3.34256:  30%|███       | 15/50 [01:09<01:26,  2.46s/it]

[I 2026-03-31 12:56:38,502] Trial 14 finished with value: 3.6869522471593745 and parameters: {'n_estimators': 190, 'max_depth': 21, 'learning_rate': 0.3311866145278467, 'subsample': 0.9118180602087038, 'min_child_weight': 19, 'min_split_gain': 5.3988873466134795, 'reg_lambda': 50.52887986465466}. Best is trial 9 with value: 3.3425557944839808.
🏃 View run exultant-finch-231 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/cdfe55aae10049629081a83fb91d4919
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 9. Best value: 3.34256:  32%|███▏      | 16/50 [01:20<02:50,  5.02s/it]

[I 2026-03-31 12:56:49,459] Trial 15 finished with value: 3.7213936702938795 and parameters: {'n_estimators': 81, 'max_depth': 6, 'learning_rate': 0.6892713751623277, 'subsample': 0.7811052454515804, 'min_child_weight': 20, 'min_split_gain': 3.1420439502266095, 'reg_lambda': 80.11296584270677}. Best is trial 9 with value: 3.3425557944839808.
🏃 View run inquisitive-cat-894 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/a031a9d6f2e44ad2ac104b3e33a5199b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 9. Best value: 3.34256:  34%|███▍      | 17/50 [01:31<03:44,  6.80s/it]

[I 2026-03-31 12:57:00,401] Trial 16 finished with value: 3.5762494205115174 and parameters: {'n_estimators': 58, 'max_depth': 39, 'learning_rate': 0.35666101095026426, 'subsample': 0.8337547833213349, 'min_child_weight': 16, 'min_split_gain': 3.193516368086039, 'reg_lambda': 69.14524511679802}. Best is trial 9 with value: 3.3425557944839808.
🏃 View run unique-cub-869 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/149e3a4392df497cb6af04d48765a17e
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run sincere-mole-313 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/7baf2ef6518a46a888bac46874c14109
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run puzzled-ant-329 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/f3e2361d2fec46fa830183f5f0ec0e97
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run fearless-yak-905 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/5ee7ddeab8bd4a1e81a5a3eb5d8db8fe
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run valuable-snail-176 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/c514aefbaa0f49adb2d45f077263b2a0
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 17. Best value: 3.28444:  36%|███▌      | 18/50 [01:41<04:08,  7.77s/it]

[I 2026-03-31 12:57:10,449] Trial 17 finished with value: 3.2844420092269657 and parameters: {'n_estimators': 22, 'max_depth': 40, 'learning_rate': 0.5100247188833109, 'subsample': 0.6774577958994438, 'min_child_weight': 7, 'min_split_gain': 0.11893957403315397, 'reg_lambda': 49.909978509807175}. Best is trial 17 with value: 3.2844420092269657.
🏃 View run sassy-lark-862 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/bd27070814f6430482dc8db2389d07a5
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 17. Best value: 3.28444:  38%|███▊      | 19/50 [01:43<03:07,  6.06s/it]

[I 2026-03-31 12:57:12,497] Trial 18 finished with value: 3.3506888320220183 and parameters: {'n_estimators': 15, 'max_depth': 40, 'learning_rate': 0.5161729914879625, 'subsample': 0.6550255856879679, 'min_child_weight': 5, 'min_split_gain': 0.3289484436743475, 'reg_lambda': 48.34229885828069}. Best is trial 17 with value: 3.2844420092269657.

Best trial: 17. Best value: 3.28444:  40%|████      | 20/50 [01:45<02:24,  4.82s/it]

[I 2026-03-31 12:57:14,434] Trial 19 finished with value: 3.436945469717858 and parameters: {'n_estimators': 12, 'max_depth': 40, 'learning_rate': 0.4909442686798792, 'subsample': 0.6755151056496808, 'min_child_weight': 6, 'min_split_gain': 0.7951658737700967, 'reg_lambda': 49.14008027693085}. Best is trial 17 with value: 3.2844420092269657.

Best trial: 17. Best value: 3.28444:  42%|████▏     | 21/50 [01:46<01:47,  3.70s/it]

[I 2026-03-31 12:57:15,509] Trial 20 finished with value: 3.373649132148183 and parameters: {'n_estimators': 19, 'max_depth': 40, 'learning_rate': 0.5003870777916757, 'subsample': 0.6589651405840455, 'min_child_weight': 5, 'min_split_gain': 0.49072544113543337, 'reg_lambda': 47.87259147334607}. Best is trial 17 with value: 3.2844420092269657.

Best trial: 17. Best value: 3.28444:  44%|████▍     | 22/50 [01:48<01:28,  3.16s/it]

[I 2026-03-31 12:57:17,412] Trial 21 finished with value: 3.3041403339590696 and parameters: {'n_estimators': 22, 'max_depth': 39, 'learning_rate': 0.4857712436952201, 'subsample': 0.6529132819320171, 'min_child_weight': 5, 'min_split_gain': 0.23230967103485511, 'reg_lambda': 50.01363413199019}. Best is trial 17 with value: 3.2844420092269657.

Best trial: 17. Best value: 3.28444:  46%|████▌     | 23/50 [01:50<01:16,  2.83s/it]

[I 2026-03-31 12:57:19,474] Trial 22 finished with value: 3.34221361597361 and parameters: {'n_estimators': 20, 'max_depth': 39, 'learning_rate': 0.30110923845663123, 'subsample': 0.6851885935669553, 'min_child_weight': 5, 'min_split_gain': 0.5767486328987041, 'reg_lambda': 50.163404202981724}. Best is trial 17 with value: 3.2844420092269657.
🏃 View run wise-smelt-268 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3/runs/67e1efee7f6d4950919946513049ede5
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/3