In [1]:
import numpy as np
import pandas as pd
import data_clean_utils
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
import dagshub
import mlflow
dagshub.init(repo_owner="rahulpatel16092005",repo_name="swiggy-delivery-time-prediction",mlflow=True)
mlflow.set_tracking_uri("https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow")
mlflow.set_experiment("Exp 5 Stacking Regressor")

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Accessing as rahulpatel16092005

Initialized MLflow to track repo "rahulpatel16092005/swiggy-delivery-time-prediction"

Repository rahulpatel16092005/swiggy-delivery-time-prediction initialized!

2026/03/31 13:54:49 INFO mlflow.tracking.fluent: Experiment with name 'Exp 5 Stacking Regressor' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/8f6110065da54ca7a38bdef463900c14', creation_time=1774945492231, experiment_id='6', last_update_time=1774945492231, lifecycle_stage='active', name='Exp 5 Stacking Regressor', tags={}, workspace='default'>

In [3]:
df=pd.read_csv("swiggy_cleaned.csv")

In [4]:
df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149,short
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,BANG,25,3,friday,0,5.0,19.0,evening,20.183530,very_long
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758,short
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401,medium
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138,medium

In [5]:
# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"]

df.drop(columns=columns_to_drop, inplace=True)

df

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,32,0,10.0,morning,1.489846,short
45498,21.0,4.6,windy,jam,0,buffet,motorcycle,1.0,no,metropolitian,36,0,15.0,evening,NaN,NaN
45499,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,16,0,15.0,night,4.657195,short
45500,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,26,0,5.0,afternoon,6.232393,medium
45501,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,36,0,5.0,afternoon,12.074396,long

In [6]:
temp_df=df.copy().dropna()

In [7]:
X=temp_df.drop("time_taken",axis=1)
y=temp_df["time_taken"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (30156, 15)
Test size: (7539, 15)

In [10]:
pt=PowerTransformer()
y_train_pt=pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt=pt.transform(y_test.values.reshape(-1,1))

In [11]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [12]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [13]:
# build a preprocessor

preprocessor = ColumnTransformer(transformers=[
    ("scale", MinMaxScaler(), num_cols),
    ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",
                                     sparse_output=False), nominal_cat_cols),
    ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],
                                      encoded_missing_value=-999,
                                      handle_unknown="use_encoded_value",
                                      unknown_value=-1), ordinal_cat_cols)
],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)


preprocessor

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [14]:
X_train_trans=preprocessor.fit_transform(X_train)
X_test_trans=preprocessor.transform(X_test)

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\compose\_column_transformer.py:978: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
import optuna
from sklearn.metrics import mean_absolute_error

In [16]:
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.compose import TransformedTargetRegressor
from sklearn.ensemble import StackingRegressor

In [17]:
# build the best models

best_rf_params = {
 'n_estimators': 177,
 'criterion': 'squared_error',
 'max_depth': 14,
 'max_features': None,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_samples': 0.8349568486026413
}

best_lgbm_params = {
 'n_estimators': 55,
 'max_depth': 38,
 'learning_rate': 0.3793573829129576,
 'subsample': 0.8823899203273144,
 'min_child_weight': 18,
 'min_split_gain': 0.0366641615279395,
 'reg_lambda': 39.450748935859494
}

best_rf = RandomForestRegressor(**best_rf_params)
best_lgbm = LGBMRegressor(**best_lgbm_params)

In [18]:
def objective(trial):
    with mlflow.start_run(nested=True):
        meta_model_name = trial.suggest_categorical("model",["LR","KNN","DT"])

        if meta_model_name == "LR":
            meta = LinearRegression()

        elif meta_model_name == "KNN":
            n_neighbors_knn = trial.suggest_int("n_neighbors_knn",1,15)
            weights_knn = trial.suggest_categorical("weights_knn",["uniform","distance"])
            meta = KNeighborsRegressor(n_neighbors=n_neighbors_knn,
                                        weights=weights_knn,n_jobs=-1)

        elif meta_model_name == "DT":
            max_depth_dt = trial.suggest_int("max_depth_dt",1,10)
            min_samples_split_dt = trial.suggest_int("min_samples_split_dt",2,10)
            min_samples_leaf_dt = trial.suggest_int("min_samples_leaf_dt",1,10)
            meta = DecisionTreeRegressor(max_depth=max_depth_dt,
                                        min_samples_split=min_samples_split_dt,
                                        min_samples_leaf=min_samples_leaf_dt,
                                        random_state=42)

        # log meta model name
        mlflow.log_param("meta_model_name",meta_model_name)

        # stacking regressor
        stacking_reg = StackingRegressor(estimators=[("rf",best_rf),
                                                    ("lgbm",best_lgbm)],
                                        final_estimator=meta,
                                        cv=5,n_jobs=-1)

        # build transformed regressor
        model = TransformedTargetRegressor(regressor=stacking_reg,
                                            transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_test = model.predict(X_test_trans)

        # mean absoulte error
        error = mean_absolute_error(y_test,y_pred_test)

        # log error
        mlflow.log_metric("MAE",error)

        return error

In [19]:
# create optuna study
study = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=20,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

[I 2026-03-31 14:04:03,526] A new study created in memory with name: no-name-9b206968-31c6-450f-af83-0ce09a577426
  0%|          | 0/20 [00:00<?, ?it/s]c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run capable-bee-382 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/1259391395ba4e5a9a94376f52b7e7e9
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 0. Best value: 3.03921:   5%|▌         | 1/20 [03:28<1:06:00, 208.46s/it]

[I 2026-03-31 14:07:34,376] Trial 0 finished with value: 3.0392062057500473 and parameters: {'model': 'DT', 'max_depth_dt': 6, 'min_samples_split_dt': 9, 'min_samples_leaf_dt': 8}. Best is trial 0 with value: 3.0392062057500473.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run honorable-rat-787 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/97e6cb564a39450599a7b3b14979aaee
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 5. Best value: 3.02815:  10%|█         | 2/20 [03:49<29:28, 98.26s/it]

[I 2026-03-31 14:07:55,569] Trial 5 finished with value: 3.0281512322539923 and parameters: {'model': 'LR'}. Best is trial 5 with value: 3.0281512322539923.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run suave-snipe-279 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/99ebc15b4e4e4e15a3d939311e51bb47
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 5. Best value: 3.02815:  15%|█▌        | 3/20 [04:17<18:45, 66.19s/it]

[I 2026-03-31 14:08:23,663] Trial 1 finished with value: 4.905240197236095 and parameters: {'model': 'DT', 'max_depth_dt': 1, 'min_samples_split_dt': 8, 'min_samples_leaf_dt': 8}. Best is trial 5 with value: 3.0281512322539923.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run bright-shark-334 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/8b7bf3d3514c49c58d9b0077e5737f14
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 5. Best value: 3.02815:  20%|██        | 4/20 [04:51<14:16, 53.55s/it]

[I 2026-03-31 14:08:57,834] Trial 6 finished with value: 3.1361485177503514 and parameters: {'model': 'KNN', 'n_neighbors_knn': 14, 'weights_knn': 'distance'}. Best is trial 5 with value: 3.0281512322539923.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run amazing-hound-524 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/71c202874d0a48019dbe866d2cb8620d
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 5. Best value: 3.02815:  25%|██▌       | 5/20 [05:13<10:31, 42.12s/it]

[I 2026-03-31 14:09:19,742] Trial 7 finished with value: 3.2336083883904685 and parameters: {'model': 'KNN', 'n_neighbors_knn': 6, 'weights_knn': 'uniform'}. Best is trial 5 with value: 3.0281512322539923.
🏃 View run traveling-ray-187 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/34340731dc2940019076b3460cdad93b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 5. Best value: 3.02815:  30%|███       | 6/20 [05:14<06:35, 28.22s/it]

[I 2026-03-31 14:09:20,973] Trial 2 finished with value: 3.0855017968204845 and parameters: {'model': 'DT', 'max_depth_dt': 9, 'min_samples_split_dt': 9, 'min_samples_leaf_dt': 7}. Best is trial 5 with value: 3.0281512322539923.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run marvelous-bass-807 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/b74f1f2ab6434e1cb4fde93c8851aeb5
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 5. Best value: 3.02815:  35%|███▌      | 7/20 [05:28<05:04, 23.41s/it]

[I 2026-03-31 14:09:34,486] Trial 3 finished with value: 3.0909273117179197 and parameters: {'model': 'DT', 'max_depth_dt': 9, 'min_samples_split_dt': 6, 'min_samples_leaf_dt': 7}. Best is trial 5 with value: 3.0281512322539923.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run bold-duck-957 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/f9e07ca2895b4fea9a188d0eb9631202
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 5. Best value: 3.02815:  40%|████      | 8/20 [05:31<03:21, 16.81s/it]

[I 2026-03-31 14:09:37,148] Trial 4 finished with value: 3.0569210448952675 and parameters: {'model': 'DT', 'max_depth_dt': 8, 'min_samples_split_dt': 8, 'min_samples_leaf_dt': 10}. Best is trial 5 with value: 3.0281512322539923.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run melodic-toad-199 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/26ecdbd27a5f45c3945ad09db77db0d7
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513:  45%|████▌     | 9/20 [07:56<10:26, 56.98s/it]

[I 2026-03-31 14:12:02,455] Trial 8 finished with value: 3.02512650394313 and parameters: {'model': 'LR'}. Best is trial 8 with value: 3.02512650394313.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run colorful-shoat-717 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/eabd4109acdb4a1ba227cd2102d5d4b1
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
Best trial: 8. Best value: 3.02513:  50%|█████     | 10/20 [08:04<06:59, 41.92s/it]

[I 2026-03-31 14:12:10,648] Trial 10 finished with value: 3.1096173079775538 and parameters: {'model': 'KNN', 'n_neighbors_knn': 13, 'weights_knn': 'uniform'}. Best is trial 8 with value: 3.02512650394313.
🏃 View run enchanting-koi-737 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/7cbfc392c6e74051b0267f370fb407cf
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
Best trial: 8. Best value: 3.02513:  55%|█████▌    | 11/20 [08:07<04:28, 29.84s/it]

[I 2026-03-31 14:12:13,121] Trial 9 finished with value: 3.0290774762549235 and parameters: {'model': 'LR'}. Best is trial 8 with value: 3.02512650394313.
🏃 View run youthful-doe-773 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/e897a846003d476390b552cfe5545370
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6
🏃 View run burly-worm-935 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/923056ec54bc4702aa9501345650544d
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513:  60%|██████    | 12/20 [08:08<02:49, 21.21s/it]

[I 2026-03-31 14:12:14,598] Trial 11 finished with value: 3.0464273894559706 and parameters: {'model': 'DT', 'max_depth_dt': 8, 'min_samples_split_dt': 4, 'min_samples_leaf_dt': 10}. Best is trial 8 with value: 3.02512650394313.

Best trial: 8. Best value: 3.02513:  65%|██████▌   | 13/20 [08:09<01:45, 15.03s/it]

[I 2026-03-31 14:12:15,402] Trial 12 finished with value: 3.2262714717675545 and parameters: {'model': 'KNN', 'n_neighbors_knn': 8, 'weights_knn': 'distance'}. Best is trial 8 with value: 3.02512650394313.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run delicate-stoat-497 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/3886eaa603d844a6b2f42d16ddafca6f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513:  70%|███████   | 14/20 [08:12<01:09, 11.50s/it]

[I 2026-03-31 14:12:18,747] Trial 13 finished with value: 3.12665112506795 and parameters: {'model': 'DT', 'max_depth_dt': 10, 'min_samples_split_dt': 5, 'min_samples_leaf_dt': 7}. Best is trial 8 with value: 3.02512650394313.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run bustling-gnat-515 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/e351cdc2de4d449a9b90b85c07d4b6d6
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513:  75%|███████▌  | 15/20 [08:28<01:03, 12.73s/it]

[I 2026-03-31 14:12:34,305] Trial 15 finished with value: 3.240142142396262 and parameters: {'model': 'KNN', 'n_neighbors_knn': 8, 'weights_knn': 'distance'}. Best is trial 8 with value: 3.02512650394313.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run zealous-bat-747 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/2b626cd726524420b60d232ec16342e2
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513:  80%|████████  | 16/20 [08:40<00:50, 12.71s/it]

[I 2026-03-31 14:12:46,998] Trial 14 finished with value: 4.901178582003611 and parameters: {'model': 'DT', 'max_depth_dt': 1, 'min_samples_split_dt': 9, 'min_samples_leaf_dt': 9}. Best is trial 8 with value: 3.02512650394313.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run efficient-shrike-350 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/9db876a5f1d444f489116e65c6f9d071
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
Best trial: 8. Best value: 3.02513:  85%|████████▌ | 17/20 [09:46<01:26, 28.72s/it]

[I 2026-03-31 14:13:52,946] Trial 16 finished with value: 3.0427753538741995 and parameters: {'model': 'DT', 'max_depth_dt': 6, 'min_samples_split_dt': 5, 'min_samples_leaf_dt': 5}. Best is trial 8 with value: 3.02512650394313.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run capable-worm-240 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/0f100e5283944c2f93e0939bf58ed759
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513:  90%|█████████ | 18/20 [09:48<00:41, 20.55s/it]

[I 2026-03-31 14:13:54,474] Trial 18 finished with value: 3.0275825891724955 and parameters: {'model': 'LR'}. Best is trial 8 with value: 3.02512650394313.
🏃 View run resilient-ape-141 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/840d25f8bcca4309abe44b89be28998a
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513:  95%|█████████▌| 19/20 [09:49<00:14, 14.69s/it]

[I 2026-03-31 14:13:55,512] Trial 17 finished with value: 3.0292500389402433 and parameters: {'model': 'LR'}. Best is trial 8 with value: 3.02512650394313.

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run calm-mare-370 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/0855934c9aad4efeb29adecbbbb0d2e5
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

Best trial: 8. Best value: 3.02513: 100%|██████████| 20/20 [09:59<00:00, 29.97s/it]

[I 2026-03-31 14:14:05,557] Trial 19 finished with value: 3.0255766309909884 and parameters: {'model': 'LR'}. Best is trial 8 with value: 3.02512650394313.
🏃 View run best_model at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6/runs/bc48b81f57214aadabe4485cf3e18c4a
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/6

In [20]:
# best parameter value

best_params = study.best_params

best_params

{'model': 'LR'}

In [21]:
# parameter value counts

study.trials_dataframe()["params_model"].value_counts()

params_model
DT     9
LR     6
KNN    5
Name: count, dtype: int64

In [22]:
# mean scores for each meta estimator type

study.trials_dataframe().groupby(by="params_model")['value'].mean().sort_values()

params_model
LR     3.027461
KNN    3.189158
DT     3.477203
Name: value, dtype: float64

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error

In [25]:
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.compose import TransformedTargetRegressor
from sklearn.ensemble import StackingRegressor

In [26]:
# build the best models

best_rf_params = {
 'n_estimators': 177,
 'criterion': 'squared_error',
 'max_depth': 14,
 'max_features': None,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_samples': 0.8349568486026413
}

best_lgbm_params = {
 'n_estimators': 55,
 'max_depth': 38,
 'learning_rate': 0.3793573829129576,
 'subsample': 0.8823899203273144,
 'min_child_weight': 18,
 'min_split_gain': 0.0366641615279395,
 'reg_lambda': 39.450748935859494
}

best_rf = RandomForestRegressor(**best_rf_params)
best_lgbm = LGBMRegressor(**best_lgbm_params)

lr=LinearRegression()

In [27]:
# build the stacking regressor

stacking_reg = StackingRegressor(estimators=[("rf",best_rf),
                                            ("lgbm",best_lgbm)],
                                final_estimator=lr,
                                cv=5,n_jobs=-1)

# build transformed regressor

model = TransformedTargetRegressor(regressor=stacking_reg,
                                    transformer=pt)

# train the model
model.fit(X_train_trans,y_train)

TransformedTargetRegressor(regressor=StackingRegressor(cv=5,
                                                       estimators=[('rf',
                                                                    RandomForestRegressor(max_depth=14,
                                                                                          max_features=None,
                                                                                          max_samples=0.8349568486026413,
                                                                                          min_samples_split=10,
                                                                                          n_estimators=177)),
                                                                   ('lgbm',
                                                                    LGBMRegressor(learning_rate=0.3793573829129576,
                                                                                  max_depth=38,
                                                                                  min_child_weight=18,
                                                                                  min_split_gain=0.0366641615279395,
                                                                                  n_estimators=55,
                                                                                  reg_lambda=39.450748935859494,
                                                                                  subsample=0.8823899203273144))],
                                                       final_estimator=LinearRegression(),
                                                       n_jobs=-1),
                           transformer=PowerTransformer())

In [28]:
# get the train and test predictions

y_train_pred = model.predict(X_train_trans)
y_test_pred = model.predict(X_test_trans)

# calculate the train and test mae

train_mae = mean_absolute_error(y_train,y_train_pred)
test_mae = mean_absolute_error(y_test,y_test_pred)

# calculate the r2 scores

train_r2 = r2_score(y_train,y_train_pred)
test_r2 = r2_score(y_test,y_test_pred)

# calculate cross val scores

cv_scores = cross_val_score(model,
                            X_train_trans,
                            y_train,cv=3,
                            scoring="neg_mean_absolute_error",
                            n_jobs=-1)

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [29]:
# log with mlflow
mlflow.set_experiment("Exp 6 Final Stacking Regressor")
with mlflow.start_run():
    # set tags
    mlflow.set_tag("model","stacking regressor")

    # log parameters
    mlflow.log_params(stacking_reg.get_params())

    # log metrics
    mlflow.log_metric("train_mae",train_mae)
    mlflow.log_metric("test_mae",test_mae)
    mlflow.log_metric("train_r2",train_r2)
    mlflow.log_metric("test_r2",test_r2)
    mlflow.log_metric("cv_score",-(cv_scores.mean()))

    # log the stacking regressor
    mlflow.sklearn.log_model(stacking_reg,"model")

2026/03/31 14:21:14 INFO mlflow.tracking.fluent: Experiment with name 'Exp 6 Final Stacking Regressor' does not exist. Creating a new experiment.
2026/03/31 14:21:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/31 14:21:24 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run mercurial-ram-887 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/7/runs/5fa8be5fe7844341841d2a15c673867b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/7